'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { Topbar } from '@/components/philly/layout/Topbar'
import { BarChart3, Target, DollarSign, Users, Download, FileText, TrendingUp, Globe, Loader2, TableProperties } from 'lucide-react'
import { useToast } from '@/hooks/philly/useToast'
import { exportToCSV } from '@/lib/philly/export'

const REPORT_TEMPLATES = [
  {
    id: 'quarterly',
    title: 'Quarterly Impact',
    description: 'Comprehensive overview of project outcomes, KPIs, and beneficiary reach for the quarter.',
    icon: BarChart3,
    color: 'var(--accent)',
    colorBg: 'var(--accent-bg)',
    colorBorder: 'var(--accent-border)',
  },
  {
    id: 'sdg',
    title: 'SDG Alignment',
    description: 'Analysis of portfolio alignment with UN Sustainable Development Goals and contribution metrics.',
    icon: Target,
    color: 'var(--g)',
    colorBg: 'var(--g-bg)',
    colorBorder: 'var(--g-border)',
  },
  {
    id: 'financial',
    title: 'Financial Overview',
    description: 'Budget allocation, expenditure tracking, ROI analysis, and funding utilization rates.',
    icon: DollarSign,
    color: 'var(--o)',
    colorBg: 'var(--o-bg)',
    colorBorder: 'var(--o-border)',
  },
  {
    id: 'stakeholder',
    title: 'Stakeholder Summary',
    description: 'Executive summary tailored for board presentations with key highlights and recommendations.',
    icon: Users,
    color: 'var(--b)',
    colorBg: 'var(--b-bg)',
    colorBorder: 'var(--b-border)',
  },
  {
    id: 'performance',
    title: 'Performance Trends',
    description: 'Year-over-year performance analysis with growth metrics, trend identification, and forecasting.',
    icon: TrendingUp,
    color: 'var(--p)',
    colorBg: 'var(--p-bg)',
    colorBorder: 'var(--p-border)',
  },
  {
    id: 'regional',
    title: 'Regional Breakdown',
    description: 'Geographic distribution of projects, regional impact scores, and cross-border collaboration insights.',
    icon: Globe,
    color: 'var(--y)',
    colorBg: 'var(--y-bg)',
    colorBorder: 'var(--y-border)',
  },
]

const TYPE_LABELS: Record<string, string> = Object.fromEntries(REPORT_TEMPLATES.map(t => [t.id, t.title]))

const statusStyles: Record<string, { bg: string; txt: string; border: string }> = {
  ready: { bg: 'var(--g-bg)', txt: 'var(--g-txt)', border: 'var(--g-border)' },
  published: { bg: 'var(--g-bg)', txt: 'var(--g-txt)', border: 'var(--g-border)' },
  draft: { bg: 'var(--y-bg)', txt: 'var(--y-txt)', border: 'var(--y-border)' },
  generating: { bg: 'var(--b-bg)', txt: 'var(--b-txt)', border: 'var(--b-border)' },
  failed: { bg: 'var(--r-bg)', txt: 'var(--r-txt)', border: 'var(--r-border)' },
}

interface ApiReport {
  id: string
  title: string
  type: string
  status: 'generating' | 'ready' | 'failed' | string
  resultHtml: string | null
  createdAt: string
}

function todayString() {
  return new Date().toISOString().slice(0, 10)
}

function downloadReportHTML(report: ApiReport) {
  // Prefer the server-rendered resultHtml; fall back to a stub
  const inner = report.resultHtml && report.resultHtml.trim().length > 0
    ? report.resultHtml
    : `<h1>${report.title}</h1><p>This report has no content yet.</p>`

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${report.title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; }
  h1 { font-size: 24px; border-bottom: 2px solid #2563eb; padding-bottom: 12px; }
  h2 { font-size: 18px; margin-top: 28px; }
  table { width: 100%; border-collapse: collapse; margin: 18px 0; font-size: 13px; }
  th, td { text-align: left; padding: 8px 12px; border: 1px solid #e5e7eb; }
  th { background: #f9fafb; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; font-size: 11px; }
  .footer { margin-top: 40px; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 16px; }
</style>
</head>
<body>
  ${inner}
  <div class="footer">Generated by Philly Dashboard on ${todayString()} · Report ID: ${report.id}</div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${report.title.replace(/\s+/g, '-').toLowerCase()}.html`
  link.click()
  URL.revokeObjectURL(url)
}

export default function ReportsPage() {
  const [reports, setReports] = useState<ApiReport[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState<string | null>(null)
  const { addToast } = useToast()
  const pollRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const fetchReports = useCallback(async () => {
    try {
      const res = await fetch('/api/reports?limit=50', { cache: 'no-store' })
      const json = await res.json()
      setReports(Array.isArray(json.data) ? json.data : [])
    } catch { /* network/offline */ }
    finally { setLoading(false) }
  }, [])

  useEffect(() => {
    fetchReports()
    return () => { if (pollRef.current) clearTimeout(pollRef.current) }
  }, [fetchReports])

  // Poll while any report is still generating
  useEffect(() => {
    const anyGenerating = reports.some(r => r.status === 'generating')
    if (!anyGenerating) {
      if (pollRef.current) { clearTimeout(pollRef.current); pollRef.current = null }
      return
    }
    pollRef.current = setTimeout(fetchReports, 1500)
    return () => { if (pollRef.current) clearTimeout(pollRef.current) }
  }, [reports, fetchReports])

  async function handleGenerate(tmpl: typeof REPORT_TEMPLATES[number]) {
    if (generating) return
    setGenerating(tmpl.id)
    try {
      const res = await fetch('/api/reports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: `${tmpl.title} - ${todayString()}`,
          type: tmpl.id,
        }),
      })
      const json = await res.json().catch(() => ({}))
      if (!res.ok) {
        addToast(json.error ?? 'Failed to start report', 'error')
        return
      }
      addToast('Report queued — generating…', 'success')
      // Optimistic insert; polling will reconcile
      if (json.data) setReports(prev => [json.data as ApiReport, ...prev.filter(r => r.id !== json.data.id)])
      else fetchReports()
    } catch (err) {
      addToast(err instanceof Error ? err.message : 'Failed to start report', 'error')
    } finally {
      setGenerating(null)
    }
  }

  function handleDownload(report: ApiReport) {
    if (report.status !== 'ready') {
      addToast('Report is still generating — try again in a moment', 'info')
      return
    }
    downloadReportHTML(report)
    addToast(`Downloading ${report.title}`, 'info')
  }

  function handleExportCSV() {
    const data = reports.map(r => ({
      title: r.title,
      type: TYPE_LABELS[r.type] ?? r.type,
      generated: r.createdAt.slice(0, 10),
      status: r.status,
    }))
    if (data.length === 0) { addToast('No reports to export', 'info'); return }
    exportToCSV(data, 'reports')
    addToast('CSV exported', 'success')
  }

  return (
    <>
      <Topbar title="Reports" sub="Generate impact reports" />

      <div style={{ padding: '18px 24px 40px' }}>
        {/* Report template cards */}
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 10 }}>Report Templates</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 12 }}>
            {REPORT_TEMPLATES.map(tmpl => {
              const Icon = tmpl.icon
              const isGenerating = generating === tmpl.id
              return (
                <div key={tmpl.id} className="card-hover" style={{
                  background: 'var(--panel)', border: '1px solid var(--border)',
                  borderRadius: 12, padding: '18px 16px',
                  boxShadow: 'var(--shadow-sm)',
                  display: 'flex', flexDirection: 'column', gap: 10,
                }}>
                  <div style={{
                    width: 36, height: 36, borderRadius: 9,
                    background: tmpl.colorBg, border: `1px solid ${tmpl.colorBorder}`,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                  }}>
                    <Icon size={18} color={tmpl.color} />
                  </div>
                  <div style={{ fontSize: 14, fontWeight: 600 }}>{tmpl.title}</div>
                  <div style={{ fontSize: 11.5, color: 'var(--txt3)', lineHeight: 1.45, flex: 1 }}>
                    {tmpl.description}
                  </div>
                  <button
                    disabled={isGenerating || generating !== null}
                    onClick={() => handleGenerate(tmpl)}
                    style={{
                      display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                      padding: '7px 14px', borderRadius: 8,
                      fontSize: 12, fontWeight: 600,
                      cursor: isGenerating || generating !== null ? 'not-allowed' : 'pointer',
                      background: isGenerating ? 'var(--accent-border)' : 'var(--accent)',
                      color: '#fff',
                      border: 'none', boxShadow: 'var(--shadow-sm)',
                      fontFamily: 'inherit', width: '100%',
                      opacity: generating !== null && !isGenerating ? 0.5 : 1,
                      transition: 'opacity 0.15s, background 0.15s',
                    }}>
                    {isGenerating ? (
                      <Loader2 size={12} style={{ animation: 'spin 1s linear infinite' }} />
                    ) : (
                      <FileText size={12} />
                    )}
                    {isGenerating ? 'Queueing...' : 'Generate'}
                  </button>
                </div>
              )
            })}
          </div>
        </div>

        {/* Recent Reports table */}
        <div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
            <div style={{ fontSize: 13, fontWeight: 600 }}>Recent Reports</div>
            <button
              onClick={handleExportCSV}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 5,
                padding: '5px 12px', borderRadius: 7,
                fontSize: 11, fontWeight: 600, cursor: 'pointer',
                background: 'var(--bg2)', color: 'var(--txt2)',
                border: '1px solid var(--border)', fontFamily: 'inherit',
              }}>
              <TableProperties size={11} /> Export All CSV
            </button>
          </div>
          <div style={{
            background: 'var(--panel)', border: '1px solid var(--border)',
            borderRadius: 12, overflow: 'hidden', boxShadow: 'var(--shadow-sm)',
          }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border)' }}>
                  {['Report Name', 'Type', 'Generated', 'Status', 'Actions'].map(h => (
                    <th key={h} style={{
                      padding: '10px 14px', textAlign: 'left', fontSize: 10.5,
                      fontWeight: 600, textTransform: 'uppercase', color: 'var(--txt3)',
                      letterSpacing: '0.05em',
                    }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {loading ? (
                  <tr><td colSpan={5} style={{ padding: 32, textAlign: 'center', color: 'var(--txt3)', fontSize: 13 }}>Loading…</td></tr>
                ) : reports.length === 0 ? (
                  <tr><td colSpan={5} style={{ padding: 32, textAlign: 'center', color: 'var(--txt3)', fontSize: 13 }}>
                    No reports yet — click <strong>Generate</strong> on any template above to create one.
                  </td></tr>
                ) : reports.map(r => {
                  const ss = statusStyles[r.status] || statusStyles.draft
                  const isReady = r.status === 'ready'
                  return (
                    <tr key={r.id} style={{ borderBottom: '1px solid var(--border)' }}>
                      <td style={{ padding: '12px 14px', fontSize: 13, fontWeight: 600 }}>{r.title}</td>
                      <td style={{ padding: '12px 14px', fontSize: 12, color: 'var(--txt2)' }}>{TYPE_LABELS[r.type] ?? r.type}</td>
                      <td className="mono" style={{ padding: '12px 14px', fontSize: 12, color: 'var(--txt2)' }}>
                        {new Date(r.createdAt).toLocaleString([], { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })}
                      </td>
                      <td style={{ padding: '12px 14px' }}>
                        <span style={{
                          fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 6,
                          background: ss.bg, color: ss.txt, border: `1px solid ${ss.border}`,
                          textTransform: 'capitalize', display: 'inline-flex', alignItems: 'center', gap: 4,
                        }}>
                          {r.status === 'generating' && <Loader2 size={10} style={{ animation: 'spin 1s linear infinite' }} />}
                          {r.status}
                        </span>
                      </td>
                      <td style={{ padding: '12px 14px', display: 'flex', gap: 6 }}>
                        <button
                          onClick={() => handleDownload(r)}
                          disabled={!isReady}
                          style={{
                            display: 'inline-flex', alignItems: 'center', gap: 5,
                            padding: '4px 10px', borderRadius: 6,
                            fontSize: 11, fontWeight: 600,
                            cursor: isReady ? 'pointer' : 'not-allowed',
                            background: 'var(--bg2)', color: isReady ? 'var(--txt2)' : 'var(--txt3)',
                            border: '1px solid var(--border)', fontFamily: 'inherit',
                            opacity: isReady ? 1 : 0.6,
                          }}>
                          <Download size={11} /> HTML
                        </button>
                        <button
                          onClick={() => {
                            exportToCSV([{ title: r.title, type: TYPE_LABELS[r.type] ?? r.type, generated: r.createdAt.slice(0, 10), status: r.status }], r.title.replace(/\s+/g, '-').toLowerCase())
                            addToast('CSV exported', 'success')
                          }}
                          style={{
                            display: 'inline-flex', alignItems: 'center', gap: 5,
                            padding: '4px 10px', borderRadius: 6,
                            fontSize: 11, fontWeight: 600, cursor: 'pointer',
                            background: 'var(--bg2)', color: 'var(--txt2)',
                            border: '1px solid var(--border)', fontFamily: 'inherit',
                          }}>
                          <TableProperties size={11} /> CSV
                        </button>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Inline keyframe for the spinner since this is a client component */}
      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </>
  )
}
