/* Branded HTML shell for generated reports.
   ──────────────────────────────────────────────────────────────────
   Wraps a template's inner HTML in a professional, DEUS-branded
   header + footer. Operators can re-style by editing this file
   without touching individual templates.

   ## Design choices

   - Single-file CSS (inline <style>) so the HTML is portable — print
     to PDF, email as attachment, paste into a Notion page, all work.
   - System font stack — never depends on a CDN-hosted webfont
     (operators print without internet sometimes; offline-safe matters).
   - Brand colour kept to one accent line (no DEUS-blue everywhere) —
     reports look authoritative without screaming "marketing collateral".
   - Footer carries a confidentiality marker + generation timestamp +
     org name. Required by some EU enterprise procurement reviewers.
   - The `logoUrl` slot supports the org's own logo (per-tenant). Default
     to the DEUS wordmark when null.
   --------------------------------------------------------------- */

export interface RenderShellOpts {
  title: string
  orgName: string
  orgLogoUrl?: string | null
  generatedAt: Date
  /** Inner template HTML — assumed already escaped. */
  innerHtml: string
  /** Footer copy translated to the active locale.
   *  e.g. "Generated by DEUS · Confidential · {date}". */
  footerText: string
  /** Optional subtitle under the title, e.g. "Q2 2026 · 12 projects". */
  subtitle?: string
}

const SHELL_CSS = `
  :root {
    --deus-ink:    #1a1a1a;
    --deus-muted:  #6b7280;
    --deus-line:   #e5e7eb;
    --deus-soft:   #f9fafb;
    --deus-accent: #2563eb;
  }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    color: var(--deus-ink);
    margin: 0;
    padding: 0;
    line-height: 1.55;
  }
  .report-shell {
    max-width: 880px;
    margin: 32px auto;
    padding: 0 32px 64px;
  }
  .report-header {
    border-bottom: 3px solid var(--deus-accent);
    padding-bottom: 18px;
    margin-bottom: 28px;
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 24px;
  }
  .report-header__brand {
    font-size: 14px;
    font-weight: 700;
    color: var(--deus-muted);
    letter-spacing: 0.08em;
    text-transform: uppercase;
  }
  .report-header__logo {
    max-height: 36px;
    max-width: 200px;
    object-fit: contain;
  }
  .report-header__org {
    font-size: 13.5px;
    color: var(--deus-muted);
    margin-top: 4px;
  }
  .report-title {
    font-size: 28px;
    font-weight: 700;
    margin: 0 0 4px;
    color: var(--deus-ink);
  }
  .report-subtitle {
    font-size: 14px;
    color: var(--deus-muted);
    margin: 0;
  }
  h2 {
    font-size: 18px;
    font-weight: 600;
    margin: 32px 0 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--deus-line);
  }
  h3 {
    font-size: 14.5px;
    font-weight: 600;
    margin: 22px 0 8px;
    color: var(--deus-ink);
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0 24px;
    font-size: 13px;
  }
  th, td {
    text-align: left;
    padding: 9px 12px;
    border-bottom: 1px solid var(--deus-line);
  }
  th {
    background: var(--deus-soft);
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--deus-muted);
    font-size: 11px;
  }
  td.mono, .mono { font-variant-numeric: tabular-nums; }
  td.num, .num { text-align: right; font-variant-numeric: tabular-nums; }
  .stat-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 14px;
    margin: 16px 0;
  }
  .stat-card {
    border: 1px solid var(--deus-line);
    background: var(--deus-soft);
    border-radius: 8px;
    padding: 14px 16px;
  }
  .stat-card__label {
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: var(--deus-muted);
    margin-bottom: 4px;
  }
  .stat-card__value {
    font-size: 22px;
    font-weight: 700;
    color: var(--deus-ink);
    font-variant-numeric: tabular-nums;
  }
  .stat-card__hint {
    font-size: 12px;
    color: var(--deus-muted);
    margin-top: 4px;
  }
  .badge {
    display: inline-block;
    padding: 2px 9px;
    border-radius: 999px;
    font-size: 11px;
    font-weight: 600;
    background: var(--deus-soft);
    color: var(--deus-muted);
    text-transform: capitalize;
  }
  .badge--good { background: #d1fae5; color: #047857; }
  .badge--warn { background: #fef3c7; color: #92400e; }
  .badge--bad  { background: #fee2e2; color: #b91c1c; }
  .report-footer {
    margin-top: 56px;
    padding-top: 16px;
    border-top: 1px solid var(--deus-line);
    font-size: 11.5px;
    color: var(--deus-muted);
    display: flex;
    justify-content: space-between;
    gap: 16px;
  }
  .empty-state {
    padding: 32px;
    text-align: center;
    color: var(--deus-muted);
    background: var(--deus-soft);
    border-radius: 8px;
    border: 1px dashed var(--deus-line);
  }
  @media print {
    .report-shell { margin: 0; padding: 0 16px; }
    .report-header { page-break-after: avoid; }
    h2, h3 { page-break-after: avoid; }
    table { page-break-inside: avoid; }
  }
`

/** HTML-escape user-supplied strings (org name, project titles, etc.).
 *  Template authors should pass user data through this — the shell
 *  doesn't trust upstream input. */
export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/** Wrap inner template HTML in the branded shell. */
export function renderShell(opts: RenderShellOpts): string {
  const safeOrgName = escapeHtml(opts.orgName)
  const safeTitle = escapeHtml(opts.title)
  const safeSubtitle = opts.subtitle ? escapeHtml(opts.subtitle) : null
  const safeFooter = escapeHtml(opts.footerText)
  const logoBlock = opts.orgLogoUrl
    ? `<img class="report-header__logo" src="${escapeHtml(opts.orgLogoUrl)}" alt="${safeOrgName}" />`
    : `<div class="report-header__brand">DEUS</div>`

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${safeTitle} — ${safeOrgName}</title>
<style>${SHELL_CSS}</style>
</head>
<body>
  <div class="report-shell">
    <header class="report-header">
      <div>
        <h1 class="report-title">${safeTitle}</h1>
        ${safeSubtitle ? `<p class="report-subtitle">${safeSubtitle}</p>` : ''}
        <div class="report-header__org">${safeOrgName}</div>
      </div>
      <div>${logoBlock}</div>
    </header>
    <main>
      ${opts.innerHtml}
    </main>
    <footer class="report-footer">
      <span>${safeFooter}</span>
      <span>${opts.generatedAt.toISOString().slice(0, 10)}</span>
    </footer>
  </div>
</body>
</html>`
}
